### ISSUE TITLE
[QST]Stuck at DataLoader Step

### ISSUE THREAD

**Issue by sumitsidana** [NVIDIA-Merlin/Transformers4Rec#403] opened 2022-04-07 16:15 UTC
# ❓ Questions & Help

## Details

Hi,

What does input data look like? Currently, I have sessions based data in Pandas DataFrame. I am following RecSys 21 tutorial and currently stuck at 8th cell of [this notbook](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/tutorial/03-Session-based-recsys.ipynb) at data loading step. How do I go from having data in Pandas DataFrame to be able to load it in the library for training?

Note: At the moment, I don't have GPU access and I can't get cudf installed on my SageMaker Studio notebook. I want to execute Transformers4Rec on CPU.

**Comment by rnyak** [comment] 2022-04-08 16:32
@sumitsidana you can preprocess your raw  df  with NVTabular library on CPU and save the processed files as parquet as demonstrated here [in this example](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/tutorial/02-ETL-with-NVTabular.ipynb) Once you save the processed df as parquet file, you can then feed it easily to the model as directed in the `03-Session-based-recsys.ipynb` nb.

if you already created sequential features with pandas,  just save your pandas dataframe as parquet, and run the cells in the `03-Session-based-recsys.ipynb` nb.

**Comment by sumitsidana** [comment] 2022-04-09 11:32
Thank you @rnyak for your support. I will try what you said using Pandas. It would also be nice if I can install cudf on SageMaker studio. Even with active AWS support, we haven't managed to install cudf and thus can't actively used NVTabular library.

**Comment by rnyak** [comment] 2022-04-10 19:45
@sumitsidana if you'll have access to GPU on Sagemaker you can use Merlin containers which have cuDF, NVTabular, Transformers4Rec, Merlin Models, Merlin core etc.  Please visit this page:

https://catalog.ngc.nvidia.com/containers?filters=&orderBy=dateModifiedDESC&query=merlin

```
docker pull nvcr.io/nvidia/merlin/merlin-pytorch-training:22.04
```

Or you can refer to conda installation on AWS SageMaker instructions here:

https://github.com/NVIDIA-Merlin/NVTabular/blob/main/docs/source/resources/cloud_integration.md#aws-sagemaker

**Comment by rnyak** [comment] 2022-04-19 14:51
@sumitsidana are you still stuck at the data loader step? did the answer above help?

**Comment by sumitsidana** [comment] 2022-04-19 14:56
Hi @rnyak yes, indeed, your answer has been helpful. But, I am at stuck at the step where I have to use ```pyarrow```. I am not sure, where I have to replace that. If you could provide an example of that, it would be helpful. But, otherwise, I don't have access to GPU at the moment.

**Comment by sumitsidana** [comment] 2022-04-20 01:02
@rnyak the above issue related to ```pyarrow``` was solved. I am stuck on a different error during the training now.

**Comment by rnyak** [comment] 2022-04-20 01:26
@sumitsidana can you please share your error and your code? thanks.

**Comment by sumitsidana** [comment] 2022-04-21 01:36
Hi @rnyak ,

I am getting the following error:

```
***** Running training *****
  Num examples = 1000192
  Num Epochs = 3
  Instantaneous batch size per device = 256
  Total train batch size (w. parallel, distributed & accumulation) = 256
  Gradient Accumulation steps = 1
  Total optimization steps = 11721
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<timed exec> in <module>

/opt/conda/lib/python3.7/site-packages/transformers/trainer.py in train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
   1420                         tr_loss_step = self.training_step(model, inputs)
   1421                 else:
-> 1422                     tr_loss_step = self.training_step(model, inputs)
   1423 
   1424                 if (

/opt/conda/lib/python3.7/site-packages/transformers/trainer.py in training_step(self, model, inputs)
   2009 
   2010         with self.autocast_smart_context_manager():
-> 2011             loss = self.compute_loss(model, inputs)
   2012 
   2013         if self.args.n_gpu > 1:

/opt/conda/lib/python3.7/site-packages/transformers/trainer.py in compute_loss(self, model, inputs, return_outputs)
   2041         else:
   2042             labels = None
-> 2043         outputs = model(**inputs)
   2044         # Save past state if it exists
   2045         # TODO: this needs to be fixed and made cleaner later.

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1108         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110             return forward_call(*input, **kwargs)
   1111         # Do not call functions when jit is used
   1112         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/transformers4rec/torch/trainer.py in forward(self, *args, **kwargs)
    786     def forward(self, *args, **kwargs):
    787         inputs = kwargs
--> 788         return self.module(inputs, *args)

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1108         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110             return forward_call(*input, **kwargs)
   1111         # Do not call functions when jit is used
   1112         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/transformers4rec/torch/model/base.py in forward(self, inputs, training, **kwargs)
    520         outputs = {}
    521         for head in self.heads:
--> 522             outputs.update(head(inputs, call_body=True, training=training, always_output_dict=True))
    523 
    524         if len(outputs) == 1:

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1108         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110             return forward_call(*input, **kwargs)
   1111         # Do not call functions when jit is used
   1112         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/transformers4rec/torch/model/base.py in forward(self, body_outputs, training, call_body, always_output_dict, **kwargs)
    386 
    387         if call_body:
--> 388             body_outputs = self.body(body_outputs, training=training)
    389 
    390         for name, task in self.prediction_task_dict.items():

/opt/conda/lib/python3.7/site-packages/transformers4rec/config/schema.py in __call__(self, *args, **kwargs)
     48         self.check_schema()
     49 
---> 50         return super().__call__(*args, **kwargs)
     51 
     52     def _maybe_set_schema(self, input, schema):

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1108         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110             return forward_call(*input, **kwargs)
   1111         # Do not call functions when jit is used
   1112         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/transformers4rec/torch/block/base.py in forward(self, input, training, **kwargs)
    149 
    150             elif "training" in inspect.signature(module.forward).parameters:
--> 151                 input = module(input, training=training)
    152             else:
    153                 input = module(input)

/opt/conda/lib/python3.7/site-packages/transformers4rec/config/schema.py in __call__(self, *args, **kwargs)
     48         self.check_schema()
     49 
---> 50         return super().__call__(*args, **kwargs)
     51 
     52     def _maybe_set_schema(self, input, schema):

/opt/conda/lib/python3.7/site-packages/transformers4rec/torch/tabular/base.py in __call__(self, inputs, pre, post, merge_with, aggregation, *args, **kwargs)
    379 
    380         # This will call the `forward` method implemented by the super class.
--> 381         outputs = super().__call__(inputs, *args, **kwargs)  # noqa
    382 
    383         if isinstance(outputs, dict):

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1108         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110             return forward_call(*input, **kwargs)
   1111         # Do not call functions when jit is used
   1112         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/transformers4rec/torch/features/sequence.py in forward(self, inputs, training, **kwargs)
    249 
    250     def forward(self, inputs, training=True, **kwargs):
--> 251         outputs = super(TabularSequenceFeatures, self).forward(inputs)
    252 
    253         if self.masking or self.projection_module:

/opt/conda/lib/python3.7/site-packages/transformers4rec/torch/tabular/base.py in forward(self, inputs, training, **kwargs)
    591         outputs = {}
    592         for layer in self.merge_values:
--> 593             outputs.update(layer(inputs))
    594 
    595         return outputs

/opt/conda/lib/python3.7/site-packages/transformers4rec/config/schema.py in __call__(self, *args, **kwargs)
     48         self.check_schema()
     49 
---> 50         return super().__call__(*args, **kwargs)
     51 
     52     def _maybe_set_schema(self, input, schema):

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1108         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110             return forward_call(*input, **kwargs)
   1111         # Do not call functions when jit is used
   1112         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/transformers4rec/torch/block/base.py in forward(self, input, training, **kwargs)
    151                 input = module(input, training=training)
    152             else:
--> 153                 input = module(input)
    154 
    155         return input

/opt/conda/lib/python3.7/site-packages/transformers4rec/config/schema.py in __call__(self, *args, **kwargs)
     48         self.check_schema()
     49 
---> 50         return super().__call__(*args, **kwargs)
     51 
     52     def _maybe_set_schema(self, input, schema):

/opt/conda/lib/python3.7/site-packages/transformers4rec/torch/tabular/base.py in __call__(self, inputs, pre, post, merge_with, aggregation, *args, **kwargs)
    383         if isinstance(outputs, dict):
    384             outputs = self.post_forward(
--> 385                 outputs, transformations=post, merge_with=merge_with, aggregation=aggregation
    386             )
    387 

/opt/conda/lib/python3.7/site-packages/transformers4rec/torch/tabular/base.py in post_forward(self, inputs, transformations, merge_with, aggregation)
    341             schema = getattr(self, "schema", None)
    342             _aggregation.set_schema(schema)
--> 343             return _aggregation(outputs)
    344 
    345         return outputs

/opt/conda/lib/python3.7/site-packages/transformers4rec/config/schema.py in __call__(self, *args, **kwargs)
     48         self.check_schema()
     49 
---> 50         return super().__call__(*args, **kwargs)
     51 
     52     def _maybe_set_schema(self, input, schema):

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1108         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110             return forward_call(*input, **kwargs)
   1111         # Do not call functions when jit is used
   1112         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/transformers4rec/torch/tabular/aggregation.py in forward(self, inputs)
     45             tensors.append(val)
     46 
---> 47         return torch.cat(tensors, dim=-1)
     48 
     49     def forward_output_size(self, input_size):

NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a fallback function.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Python, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradLazy, AutogradXPU, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, AutocastCPU, Autocast, Batched, VmapMode, Functionalize].

CPU: registered at aten/src/ATen/RegisterCPU.cpp:21063 [kernel]
CUDA: registered at aten/src/ATen/RegisterCUDA.cpp:29726 [kernel]
QuantizedCPU: registered at aten/src/ATen/RegisterQuantizedCPU.cpp:1258 [kernel]
BackendSelect: fallthrough registered at ../aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:47 [backend fallback]
Named: registered at ../aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at ../aten/src/ATen/ConjugateFallback.cpp:18 [backend fallback]
Negative: registered at ../aten/src/ATen/native/NegateFallback.cpp:18 [backend fallback]
ZeroTensor: registered at ../aten/src/ATen/ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:64 [backend fallback]
AutogradOther: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradCPU: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradCUDA: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradXLA: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradLazy: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradXPU: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradMLC: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradHPU: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradNestedTensor: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradPrivateUse1: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradPrivateUse2: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradPrivateUse3: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
Tracer: registered at ../torch/csrc/autograd/generated/TraceType_3.cpp:11220 [kernel]
AutocastCPU: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:461 [backend fallback]
Autocast: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:305 [backend fallback]
Batched: registered at ../aten/src/ATen/BatchingRegistrations.cpp:1059 [backend fallback]
VmapMode: fallthrough registered at ../aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
Functionalize: registered at ../aten/src/ATen/FunctionalizeFallbackKernel.cpp:52 [backend fallback]
```
When running:

```
%%time
start_time_window_index = 1
final_time_window_index = 2
for time_index in range(start_time_window_index, final_time_window_index):
    # Set data 
    time_index_train = time_index
    time_index_eval = time_index + 1
    train_paths = glob.glob(os.path.join(OUTPUT_DIR, f"{time_index_train}/input.parquet"))
#     eval_paths = glob.glob(os.path.join(OUTPUT_DIR, f"{time_index_eval}/valid.parquet"))
    print(os.path.join(OUTPUT_DIR, f"{time_index_train}/input.parquet"))
    print(train_paths)
#     print(eval_paths)
    # Train on day related to time_index 
    print('*'*20)
    print("Launch training for day %s are:" %time_index)
    print('*'*20 + '\n')
    trainer.train_dataset_or_path = train_paths
    trainer.reset_lr_scheduler()
    trainer.train()
    trainer.state.global_step +=1
    # Evaluate on the following day
#     trainer.eval_dataset_or_path = eval_paths
#     train_metrics = trainer.evaluate(metric_key_prefix='eval')
#     print('*'*20)
#     print("Eval results for day %s are:\t" %time_index_eval)
#     print('\n' + '*'*20 + '\n')
#     for key in sorted(train_metrics.keys()):
#         print(" %s = %s" % (key, str(train_metrics[key]))) 
#     wipe_memory()
```

**Comment by rnyak** [comment] 2022-04-21 13:20
@sumitsidana are you using one of our training examples with the data we provide? if yes which one? 

If no, can you please share  you entire code (including your NVT code, your dataloader commands, etc etc.. ) please in a gist file may be? Also a simple fake dataset that similar to your dataset, , and your schema.pb file as well?  we cannot reproduce your error only with training code..

Besides, how do you generate your schema file in case you are using a custom dataset?  Thanks.

**Comment by sumitsidana** [comment] 2022-04-27 12:28
Hi @rnyak I am using RecSys 2022 challenge data set. Here is the link to the gist: https://gist.github.com/sumitsidana/fe45069fff6e5bf516b42a76b00263c3

I have added head of the data and how I create schema file. Please let me know if it still not clear. Thanks.

**Comment by rnyak** [comment] 2022-05-09 18:51
@sumitsidana can you please follow this unit test example?

https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/tests/torch/test_trainer.py#L59-L75

let us know if you still have any issues. Thanks.

**Comment by rnyak** [comment] 2022-07-25 13:51
@sumitsidana we are closing this issue since we did not hear from you. Please reopen if you still have a question.

**Closed by rnyak** 2022-07-25 13:51 UTC
Labels: status/needs-triage

**Comment by alan-ai-learner** [comment] 2023-02-20 11:41
Hi @rnyak , I'm trying to train the t4rec on youchoose similar dataset and it is giving me cuda error everytime i ran it.
I'm following the example tutorial where you are using youchoose dataset.

Everything i followed is same and did for youchoose dataset but i'm not sure why the error coming.

Errror:
```
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

```
but no error on you choose dataset
