### ISSUE TITLE
[QST]IndexError: too many indices for tensor of dimension 2

### ISSUE THREAD

**Issue by DilipKumar3** [NVIDIA-Merlin/Transformers4Rec#584] opened 2022-12-21 15:55 UTC
# ❓ Questions & Help
As a part of exploration i'm running the code for transform4rec model built on synthetic data [https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/getting-started-session-based/02-session-based-XLNet-with-PyT.ipynb]

throwing exception while running the below code.
![image](https://user-images.githubusercontent.com/48671630/208946632-9d7e2aa8-5d84-4ff6-baaf-31cab020a9fc.png)
and the error is 
![image](https://user-images.githubusercontent.com/48671630/208946809-244de783-80a7-41f1-bf30-4ed8d5927da9.png)
Based on my understanding the error occurs on evaluation step where input file is not in required dimension.
## Details
this is my path for train,valid,and test files
![image](https://user-images.githubusercontent.com/48671630/208947227-4d96dac7-6b59-4f6a-a44c-61c0a72dfdfe.png)

**Comment by rnyak** [comment] 2022-12-27 13:39
@DilipKumar3 how do you install `Transformers4rec`, `NVtabular`, `core` and `dataloader` libraries? you need all of them. I think you are not using docker image, do you? so please install the latest versions of these libraries. 

I cannot reproduce your error. I can run the notebooks without error. if you are running 01-ETL and 02-session-based-XLNet without changing anything, they should run fine.  My guess you need to reinstall the libraries again from main branch.

**Comment by rnyak** [comment] 2023-01-13 13:31
closing since there is no further activity.

**Closed by rnyak** 2023-01-13 13:31 UTC
Labels: status/needs-triage

**Comment by ravikant15796** [comment] 2023-01-17 03:33
@DilipKumar3 have you found any solution for this error ? I am also getting similar issue

**Comment by rnyak** [comment] 2023-01-17 18:40
@ravikant15796 what's your env? how did you install transformers4rec, nvtabular, dataloader, and core?
