### ISSUE TITLE
[BUG] Schema error in tutorial

### ISSUE THREAD

**Issue by maktukmak** [NVIDIA-Merlin/Transformers4Rec#478] opened 2022-08-22 23:51 UTC
### Bug description
Following Tutorial: End-to-end Session-based Recommendation gives the following error.

### Steps/Code to reproduce bug
1. Run codes on Preliminary processing section
2. Run codes on ETL section
3. Run: "schema = Schema().from_proto_text(SCHEMA_PATH)"

### Environment details
- Transformers4Rec version: 0.1.4
- Platform: Linux
- Python version: 3.7
- Huggingface Transformers version: 4.12.5
- PyTorch version (GPU?):  1.12.1 (gpu)
- Tensorflow-metadata version : 1.2.0

### Error
Traceback (most recent call last):
  File "/media/MERCURY/mehmet/anaconda3/envs/merlin37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/media/MERCURY/mehmet/anaconda3/envs/merlin37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/MERCURY/mehmet/.vscode-server/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/media/MERCURY/mehmet/.vscode-server/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/media/MERCURY/mehmet/.vscode-server/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/media/MERCURY/mehmet/.vscode-server/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 322, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/media/MERCURY/mehmet/.vscode-server/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 136, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/media/MERCURY/mehmet/.vscode-server/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/media/MERCURY/mehmet/tutorials/t4rec_tut_sess.py", line 14, in <module>
    schema = Schema().from_proto_text(SCHEMA_PATH)
  File "/media/MERCURY/mehmet/anaconda3/envs/merlin37/lib/python3.7/site-packages/merlin_standard_lib/schema/schema.py", line 404, in from_proto_text
    return proto_utils.proto_text_to_better_proto(self, path_or_proto_text, schema_pb2.Schema())
  File "/media/MERCURY/mehmet/anaconda3/envs/merlin37/lib/python3.7/site-packages/merlin_standard_lib/utils/proto_utils.py", line 55, in proto_text_to_better_proto
    proto = text_format.Parse(proto_text, message)
  File "/media/MERCURY/mehmet/anaconda3/envs/merlin37/lib/python3.7/site-packages/google/protobuf/text_format.py", line 687, in Parse
    allow_unknown_field=allow_unknown_field)
  File "/media/MERCURY/mehmet/anaconda3/envs/merlin37/lib/python3.7/site-packages/google/protobuf/text_format.py", line 759, in ParseLines
    return parser.ParseLines(lines, message)
  File "/media/MERCURY/mehmet/anaconda3/envs/merlin37/lib/python3.7/site-packages/google/protobuf/text_format.py", line 812, in ParseLines
    self._ParseOrMerge(lines, message)
  File "/media/MERCURY/mehmet/anaconda3/envs/merlin37/lib/python3.7/site-packages/google/protobuf/text_format.py", line 837, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/media/MERCURY/mehmet/anaconda3/envs/merlin37/lib/python3.7/site-packages/google/protobuf/text_format.py", line 934, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 1:1 : Message type "tensorflow.metadata.v0.Schema" has no field named "schema_tutorial".

**Comment by rnyak** [comment] 2022-08-25 18:15
@maktukmak thanks for reporting this. I am not able to reproduce this error. I can read the schema file without any error. I am using `merlin-pytorch:22.07` docker image.

can you tell us how did you install Transformers4Rec library? are you using a docker image or did you install via conda? 
If not docker image, please pay attention to the requirements [here](https://github.com/NVIDIA-Merlin/Transformers4Rec/tree/main/requirements).

**Comment by rnyak** [comment] 2022-09-09 17:36
@maktukmak closing this ticket since we did not hear back from you. you can reopen if the issue still remains. thanks.

**Closed by rnyak** 2022-09-09 17:36 UTC
Labels: bug, status/needs-triage, P2
