### ISSUE TITLE
[QST] Get item's original string values from Categorical var in Triton

### ISSUE THREAD

**Issue by denisov-vlad** [NVIDIA-Merlin/Transformers4Rec#511] opened 2022-10-29 15:48 UTC
# ❓ Questions & Help

## Details

Hi.

I've trained t4r model and set up triton inference. The ensemble's model output is an array sorted according to the order of the Categorical variable. Is it possible to return Categorical values here as second output?

**Comment by rnyak** [comment] 2022-11-29 18:04
> Is it possible to return Categorical values here as second output?
@denisov-vlad  if I understand correctly, would you like to return the original item ids instead of encoded item ids? We do not have a utility funct for that so for now it'd require manual conversion. All the original ids and mapped ids are stored automatically as parquet file in `categories` folder once you run Categorify. you can create a simple mapping func to map the encoded ids to original ids..

hope that helps.

**Comment by rnyak** [comment] 2023-01-11 16:53
@denisov-vlad I am closing this issue for now. if you have other questions please re-open this ticket.

**Closed by rnyak** 2023-01-11 16:53 UTC
Labels: status/needs-triage

**Comment by denisov-vlad** [comment] 2023-01-31 11:10
@rnyak 

Hi! 

Thanks for the answers. I'm almost done working on this problem.

But I have one question about `item` shapes. Noticed that it's different in config.pbtxt and in `t4r_pytorch_nvt/N/workflow/categories/XXX.parquet`. The number in config is always equals number from parquet + 1.

I've found this both in my data and tutorial example (with first 20m rows of original file).

Merlin-Pytorch version: 22.12. The text below is from `tutorial` results:


/workspace/models/t4r_pytorch/config.pbtxt
```
output {
  name: "output"
  data_type: TYPE_FP32
  dims: -1
  dims: 118335
}
```


```
items = cudf.read_parquet("/workspace/models/t4r_pytorch_nvt/1/workflow/categories/unique.product_id.parquet")
items.shape
> (118334, 2)
```

Is it a bug?

**Comment by rnyak** [comment] 2023-01-31 13:27
@denisov-vlad  this is not a bug.  Normally, we add +1 for out of vocabularies and nulls in the cardinality so that embedding table size is `1 + n_unique_items` where the first line is for OOV+nulls (in case you have any in your train set). you wont have OOVs in your train set but you might have in your valid set and they are mapped to 0. 

if you used `start_index =1` in the `Categorify()` op then your item_id encoding starts from 2 not 1. Because we reserve 0 for padding, 1 for OOV +nulls, and then the other item categories starts from 2. so in that case, you will get `2 + n_unique_items` from your prediction results.

**Comment by denisov-vlad** [comment] 2023-01-31 14:22
Thanks!

**Comment by denisov-vlad** [comment] 2023-01-31 14:26
@rnyak thanks!
