### ISSUE TITLE
[QST] InferenceServerException: IndexError: tuple index out of range

### ISSUE THREAD

**Issue by dhollier** [NVIDIA-Merlin/Transformers4Rec#597] opened 2023-01-06 20:15 UTC
# ❓ Questions & Help
I've built a model using a custom dataset, and I've run into an error at the Triton Inference Server stage.

<img width="1313" alt="Screen Shot 2023-01-06 at 11 43 38 AM" src="https://user-images.githubusercontent.com/13304429/211087942-c2f6bbb8-6315-4846-872b-9c4656678ff1.png">

I'm unsure where to begin debugging this error.

**Comment by rnyak** [comment] 2023-01-09 17:47
@dhollier can you please share more about your env? are you using `merlin-pytorch` docker image? if yes which version?  

Besides, we need more to reproduce this error. you can share a fake dataset and your etl and training pipeline  so that we can repro this error. thanks.

**Comment by dhollier** [comment] 2023-01-10 17:53
Hi @rnyak 

Yes I'm using merlin-pytorch version 22.12.

I'm working to put together the a fake dataset I should have that done soon.

**Comment by dhollier** [comment] 2023-01-10 23:32
@rnyak 

I've provided sample data and notebooks here:

https://github.com/dhollier/transformers4rec_example

Please let me know if you have issues running or if you need any additional files/info.

Thanks!

**Comment by rnyak** [comment] 2023-01-16 17:17
@dhollier hello. The schema you have in your `data` folder and the schema you generate are not the same files.  which one are you using when training your model? And  I get  `Missing columns ['pc9', 'product_item_type', 'color_group', 'action'] found in operatorSelectionOp during compute_selector.` error from your ETL. I'd recommend you to fix that first, even duh you can export `sessions_gdf`. Be sure that NVT pipeline does not give any errors .

if you export schema from NVT pipeline (this is recommended):
- you dont need to add Categorical tag columns that are already categorified (it is done automatically)
- You dont need to ad LIST tag for columns that are aggregated as list in Groupby, this is automatically added
- same for continuous, if there is a normalization op already applied, CONTINUOUS tag is automatically added.

Please take a look at this example [notebook](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/getting-started-session-based/01-ETL-with-NVTabular.ipynb) for tagging. Just some things to add to make serving on Triton work:
- add `pad=True` in the ListSlice op (you are already doing it, so keep it).
- add tag for the `day_first` to avoid any error during serving. something like that `day_index = session_time >> nvt.ops.LambdaOp(lambda col: col.dt.day) >> nvt.ops.Rename(name ='day') >> nvt.ops.AddMetadata(tags=[Tags.CATEGORICAL])`

hope that helps.

**Comment by dhollier** [comment] 2023-01-18 01:38
Hi @rnyak. 

Thanks I was able to correct the issue I was having. I believe it was related to not having value_counts in my schema for the *_seq columns in the dataset. I suspect the tuple being referred to was the min and max values for value_count. Once I cleaned up the tags and applied nvt.ops.ValueCount() to the *_seq columns the issue went a way. 

I do have 2 more questions:

1) I'm still having to remove "day" from my schema file manually. This column is being used for "partition_col" in save_time_based_splits, but is not used in the model. What is the best way for me to exclude this in schema generation, but still maintain it for use in save_time_based_splits?

2) Is there a way for me to run the model for inference without the use of Triton Server? It would be helpful if you could point me to documentation / an example of that.

**Comment by rnyak** [comment] 2023-01-18 20:55
@dhollier glad that you solved your issue. 

1. If a column, like `day-index` is exported in the NVTabular transformed dataframe (`session_gdf` in our case), we currently cannot exclude a column from schema automatically, so you should go and manually remove it. 
why do you want to remove it? it wont give you an issue.. are you getting an issue from Triton? As I wrote above, just tag `day-index`  as `nvt.ops.AddMetadata(tags=[Tags.CATEGORICAL])` . 

3. do you mean you want to do local/offline inference? If yes, you can use `trainer.predict()` for that. something like that 

```
test_paths=<set the path to your test set>
trainer.args.predict_top_k = 20  # you can change this value
prediction = trainer.predict(test_paths)
print(prediction)
```

**Comment by dhollier** [comment] 2023-01-19 23:07
1. OK I will continue to remove it manually. I didn't think that it would have much predictive value because it's just a value indicating the day of the month. I can test leaving it in.
2. Yes that's correct. This is what I was looking for Thanks!

**Comment by dhollier** [comment] 2023-01-19 23:08
I've actually run into another issue I believe may be related to my schema set up. I'm now getting the following error from Triton when predicting on data from an unseen day. I'm able to run Triton on days that I trained on, but not on days that haven't been trained.

This is the error that the notebook produces:

`---------------------------------------------------------------------------
InferenceServerException                  Traceback (most recent call last)
Cell In[147], line 15
     12 MODEL_NAME_NVT = "t4r_pytorch"
     14 with grpcclient.InferenceServerClient("localhost:8001") as client:
---> 15     response = client.infer(MODEL_NAME_NVT, inputs)
     16     print(col, ':\n', response.as_numpy(col))

File /usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py:1431, in InferenceServerClient.infer(self, model_name, inputs, model_version, outputs, request_id, sequence_id, sequence_start, sequence_end, priority, timeout, client_timeout, headers, compression_algorithm)
   1429     return result
   1430 except grpc.RpcError as rpc_error:
-> 1431     raise_error_grpc(rpc_error)

File /usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py:62, in raise_error_grpc(rpc_error)
     61 def raise_error_grpc(rpc_error):
---> 62     raise get_error_grpc(rpc_error) from None

InferenceServerException: [StatusCode.INTERNAL] in ensemble 't4r_pytorch', Failed to process the request(s) for model instance 't4r_pytorch_pt', message: RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

At:
  /usr/local/lib/python3.8/dist-packages/transformers/models/xlnet/modeling_xlnet.py(1067): relative_positional_encoding
  /usr/local/lib/python3.8/dist-packages/transformers/models/xlnet/modeling_xlnet.py(1215): forward
  /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(1190): _call_impl
  /usr/local/lib/python3.8/dist-packages/transformers4rec/torch/block/transformer.py(178): forward
  /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(1190): _call_impl
  /usr/local/lib/python3.8/dist-packages/transformers4rec/config/schema.py(50): __call__
  /usr/local/lib/python3.8/dist-packages/transformers4rec/torch/block/base.py(148): forward
  /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(1190): _call_impl
  /usr/local/lib/python3.8/dist-packages/transformers4rec/config/schema.py(50): __call__
  /usr/local/lib/python3.8/dist-packages/transformers4rec/torch/model/base.py(379): forward
  /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(1190): _call_impl
  /usr/local/lib/python3.8/dist-packages/transformers4rec/torch/model/base.py(563): forward
  /usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py(1190): _call_impl
  /root/notebooks/../models/t4r_pytorch_pt/1/model.py(172): execute
`

This is the error I see in the terminal running Triton:

`root@c21b7c0bf9da:~/notebooks# tritonserver --model-repository=../models --model-control-mode=explicit
I0119 22:08:06.601391 2671 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7f5994000000' with size 268435456
I0119 22:08:06.604837 2671 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
I0119 22:08:06.609251 2671 server.cc:563] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0119 22:08:06.609298 2671 server.cc:590] 
+---------+------+--------+
| Backend | Path | Config |
+---------+------+--------+
+---------+------+--------+

I0119 22:08:06.609339 2671 server.cc:633] 
+-------+---------+--------+
| Model | Version | Status |
+-------+---------+--------+
+-------+---------+--------+

I0119 22:08:06.834305 2671 metrics.cc:864] Collecting metrics for GPU 0: Tesla T4
I0119 22:08:06.834894 2671 metrics.cc:757] Collecting CPU metrics
I0119 22:08:06.835275 2671 tritonserver.cc:2264] 
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                  |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                 |
| server_version                   | 2.28.0                                                                                                                                 |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory  |
|                                  | cuda_shared_memory binary_tensor_data statistics trace logging                                                                         |
| model_repository_path[0]         | ../models                                                                                                                              |
| model_control_mode               | MODE_EXPLICIT                                                                                                                          |
| strict_model_config              | 0                                                                                                                                      |
| rate_limit                       | OFF                                                                                                                                    |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                              |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                               |
| response_cache_byte_size         | 0                                                                                                                                      |
| min_supported_compute_capability | 6.0                                                                                                                                    |
| strict_readiness                 | 1                                                                                                                                      |
| exit_timeout                     | 30                                                                                                                                     |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------+

I0119 22:08:06.886027 2671 grpc_server.cc:4819] Started GRPCInferenceService at 0.0.0.0:8001
I0119 22:08:06.886554 2671 http_server.cc:3477] Started HTTPService at 0.0.0.0:8000
I0119 22:08:06.928800 2671 http_server.cc:184] Started Metrics Service at 0.0.0.0:8002
I0119 22:08:12.953254 2671 model_lifecycle.cc:459] loading: t4r_pytorch_pt:1
I0119 22:08:12.953347 2671 model_lifecycle.cc:459] loading: t4r_pytorch_nvt:1
I0119 22:08:28.698402 2671 python_be.cc:1856] TRITONBACKEND_ModelInstanceInitialize: t4r_pytorch_pt (GPU device 0)
I0119 22:09:10.150943 2671 python_be.cc:1856] TRITONBACKEND_ModelInstanceInitialize: t4r_pytorch_nvt (GPU device 0)
I0119 22:09:10.171269 2671 model_lifecycle.cc:694] successfully loaded 't4r_pytorch_pt' version 1
I0119 22:09:16.948284 2671 model_lifecycle.cc:694] successfully loaded 't4r_pytorch_nvt' version 1
I0119 22:09:16.949134 2671 model_lifecycle.cc:459] loading: t4r_pytorch:1
I0119 22:09:16.949415 2671 model_lifecycle.cc:694] successfully loaded 't4r_pytorch' version 1
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [1,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [2,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [3,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [4,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [5,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [6,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [7,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [8,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [9,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [10,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [11,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [12,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [13,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [14,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [15,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [16,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [17,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [18,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [19,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [20,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [21,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [22,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [23,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [24,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [25,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [26,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [27,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [28,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [29,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [30,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [31,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [32,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [33,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [34,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [35,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [36,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [37,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [38,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [39,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [40,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [41,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [42,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [43,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [44,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [45,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [46,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [47,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [48,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [49,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [50,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [51,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [52,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [53,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [54,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [55,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [56,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [57,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [58,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [59,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [60,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [61,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [62,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/pytorch/pytorch/aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [63,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
`

**Comment by rnyak** [comment] 2023-01-20 19:06
1. we are not feeding session_id to the model, are you feeding that column? so unseen session_id would not be a problem.
2. if you have unseen item_ids, that wont be a problem either since NVT is going to transform them on the fly, if you served NVT model on Triton as well.

Did you check if you are loading all the models on triton properly. do you see all your 3 models are successfully loaded on Triton?

**Comment by dhollier** [comment] 2023-01-20 20:03
1. session_id is in my schema file, I am passing in my filtered_batch dataset to create the inputs for Trition below:

```import nvtabular.inference.triton as nvt_triton
import tritonclient.grpc as grpcclient

inputs = nvt_triton.convert_df_to_triton_input(filtered_batch_eval.columns, filtered_batch_eval, grpcclient.InferInput)

output_names = ["output"]

outputs = []
for col in output_names:
    outputs.append(grpcclient.InferRequestedOutput(col))
    
MODEL_NAME_NVT = "t4r_pytorch"

with grpcclient.InferenceServerClient("localhost:8001") as client:
    response = client.infer(MODEL_NAME_NVT, inputs)
    print(col, ':\n', response.as_numpy(col))```

2. OK that is good to know. These new datasets do not contain unseen item_ids. 

All models are loaded properly:

```POST /v2/repository/index, headers None

<HTTPSocketPoolResponse status=200 headers={'content-type': 'application/json', 'content-length': '167'}>
bytearray(b'[{"name":"t4r_pytorch","version":"1","state":"READY"},{"name":"t4r_pytorch_nvt","version":"1","state":"READY"},{"name":"t4r_pytorch_pt","version":"1","state":"READY"}]')

[{'name': 't4r_pytorch', 'version': '1', 'state': 'READY'},
 {'name': 't4r_pytorch_nvt', 'version': '1', 'state': 'READY'},
 {'name': 't4r_pytorch_pt', 'version': '1', 'state': 'READY'}]```


Referencing the first stack trace in the previous message, it's not clear to me what portion of the schema is causing the error.
The only difference between getting a successful response and the error above is selecting data from a different day. All of the data has gone through the same pipeline. The input dataset has a seconds column that is converted from a timestamp. Is it possible that the seconds column becomes out of range on data from new days?

**Comment by dhollier** [comment] 2023-01-20 21:37
@rnyak  I believe it is a session_id issue in the schema. I was able to confirm by replacing the session_id values in the new data with session_ids the model has seen. 

Comparing the schema [here](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/end-to-end-session-based/02-End-to-end-session-based-with-Yoochoose-PyT.ipynb) to my schema I see a difference in tags. 

This is the schema from the tutorial:
```
feature {
  name: "session_id"
  type: INT
  int_domain {
    name: "session_id"
    min: 1
    max: 9249733 
    is_categorical: false
  }
  annotation {
    tag: "groupby_col"
  }
}
```
My session_id schema looks like this:

```
feature {
  name: "session_id"
  type: INT
  int_domain {
    name: "session_id"
    max: 3714318
    is_categorical: true
  }
  annotation {
    tag: "categorical"
    extra_metadata {
      type_url: "type.googleapis.com/google.protobuf.Struct"
      value: "\n\021\n\013num_buckets\022\002\010\000\n\033\n\016freq_threshold\022\t\021\000\000\000\000\000\000\000\000\n\025\n\010max_size\022\t\021\000\000\000\000\000\000\000\000\n\030\n\013start_index\022\t\021\000\000\000\000\000\000\360?\n5\n\010cat_path\022)\032\'.//categories/unique.session_id.parquet\nG\n\017embedding_sizes\0224*2\n\030\n\013cardinality\022\t\021\000\000\000\200\207VLA\n\026\n\tdimension\022\t\021\000\000\000\000\000\000\200@\n\034\n\017dtype_item_size\022\t\021\000\000\000\000\000\000P@\n\r\n\007is_list\022\002 \000\n\017\n\tis_ragged\022\002 \000"
    }
  }
}
```

The tutorial schema has a 'groupby_col' tag while mine is tagged as 'categorical'. It seems like session_id is being fed into my model. What is the correct way to fix this?

**Comment by rnyak** [comment] 2023-01-23 13:56
You can remove the session_id from the schema. But please note that in the tutorial nb we are creating a sub schema by selecting certain columns in the schema file `schema = schema.select_by_name(x_cat_names + x_cont_names)`, so if you are doing the same session_id should not be fed to the model. But to be safe, remove `session_id` feature from the schema file manually.

**Comment by dhollier** [comment] 2023-01-25 04:41
@rnyak 

Yes that was it. Dropping it from the schema file corrected my issue.

Thank you for all of the help!

**Comment by rnyak** [comment] 2023-01-25 14:30
@dhollier glad that it worked fine. shall we close this ticket or you have further questions?

**Closed** 2023-01-25 17:43 UTC
Labels: status/needs-triage
