### ISSUE TITLE
[BUG]Dtype discrepancy detected for column age_days-list

### ISSUE THREAD

**Issue by Reihnnnn** [NVIDIA-Merlin/Transformers4Rec#672] opened 2023-04-09 15:53 UTC
### Bug description

Run the sample code on colab, and I met this problem:
TypeError: Dtype discrepancy detected for column age_days-list: operator Groupby reported dtype `DType(name='float32', element_type=<ElementType.Float: 'float'>, element_size=32, element_unit=None, signed=True, shape=Shape(dims=None))` but returned dtype `DType(name='float64', element_type=<ElementType.Float: 'float'>, element_size=64, element_unit=None, signed=True, shape=Shape(dims=None))`.

### Steps/Code to reproduce bug

1.  Follow this script https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/getting-started-session-based/01-ETL-with-NVTabular.ipynb
2. the line "workflow.fit_transform(dataset).to_parquet(os.path.join(INPUT_DATA_DIR, "processed_nvt")" returns error

### Expected behavior

the datatype should be fine

### Environment details
- Transformers4Rec version: should be the latest, directly pip install
- Platform: colab

**Comment by rnyak** [comment] 2023-04-13 11:13
@Reihnnnn I cannot reproduce your error.  

how do you install cudf and dask_cudf?  If you are installing them via pip, you can install with the following:

`pip install rmm-cu11==22.10.0 cudf-cu11==22.10.0 dask-cudf-cu11==22.10.0 --extra-index-url=https://pypi.nvidia.com/`

you can see the installation scripts here: https://docs.rapids.ai/install#pip

Besides, please install merlin libraries using pypi package versions not from the source (meaning dev branch). for that you should do 
```
pip install merlin-core
pip install merlin-dataloader
pip install nvtabular
pip install merlin-models
pip install transformers4rec
pip install merlin-systems
```

**Comment by rnyak** [comment] 2023-06-21 17:28
@Reihnnnn I am closing this ticket due to low activity. Please reopen if you have further questions.

**Closed by rnyak** 2023-06-21 17:28 UTC
Labels: bug, status/needs-triage, P2
